spring:
  profiles:
    active: @env@
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  servlet:
    context-path: /springboottemplate
  tomcat:
    uri-encoding: UTF-8
logging:
  config: classpath:configuration/logback-spring.xml
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
project:
  property:
    group-id: @groupId@
    artifact-id: @artifactId@
    version: @version@
    name: @name@
    description: @description@
    jdk-version: @java.version@
    current-environment: @env@
jwt:
  configuration:
    ttl: 1800000
    ttl-for-remember-me: 604800000
custom:
  configuration:
    druid-login-name: ENC(v81zk6uOH72fTKZTWxbOgg==)
    druid-password: ENC(99HsmfWW2K8z3t1jUb0fZg==)
jasypt:
  encryptor:
    password: ThisIsAPrivateKeyOfJasypt
