spring:
  profiles:
    active: @env@
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  servlet:
    context-path: "/springboottemplate"
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
project:
  property:
    group-id: @groupId@
    artifact-id: @artifactId@
    version: @version@
    name: @name@
    description: @description@
    jdk-version: @java.version@
    current-environment: @env@
jwt:
  config:
    ttl: 1800000
    ttl-for-remember-me: 604800000
custom:
  configuration:
    druid-login-name: "johnny"
    druid-password: 123456
