spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: "/springboottemplate"
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
jwt:
  config:
    ttl: 1800000
    ttl-for-remember-me: 604800000
custom:
  config:
    druid-login-name: "johnny"
    druid-password: 123456
