spring:
  cache:
    cache-names: c1,c2
    redis:
      time-to-live: 1800s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: H'Tkh9@!*_/B'_j
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_template?useUnicode=true&characterEncoding=utf8
    username: spring_boot_template_w
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: sql/**/*Mapper.xml
  type-aliases-package: com.jm.springboottemplate.**.
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
jwt:
  config:
    ttl: 1800000
    ttl-for-remember-me: 604800000
custom:
  config:
    ignores:
      # POST Requests need to be ignored.
      post:
        - "/auth/register"
        - "/auth/login"
        - "/auth/logout"
      # Request need to be ignored that matches pattern.
      pattern:
        - "/swagger-resources/**"
        - "/v2/api-docs/**"
        - "/webjars/**"
        - "/swagger-ui.html"
        - "/error"
