spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: "/springboottemplate"
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  config:
    ttl: 1800000
    ttl-for-remember-me: 604800000
