server:
  port: 8080
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-store-password: ENC(Llhd3pDTnL4x1BmFutqGNJ2h3M/fw5OpKCDACf3vztgW/B2mtjle0SHqDE4XETHT)
#    key-alias: tomcat

spring:
  cache:
    cache-names: c1,c2
    redis:
      time-to-live: 1800s
  datasource:
    name: datasource-one
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://cdb-12mi7v72.bj.tencentcdb.com:10112/jm_spring_boot_template?useSSL=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: ENC(u+d031ary1vBWmoHxS32Uie6e3Sx3g18jQRrjnoNBsxGyu/lgM2kDw==)
    password: ENC(8H2ArHlSXKW7R+R5sbOS7E8ItUI+EPjU)
  devtools:
    restart:
      enabled: false
  redis:
    database: 0
    host: ENC(eDjbZ3ILecSAMjvqd+DtzfB8z0Al+D37)
    port: 6379
    password: ENC(aIqOVSt1Lsw/k1RN0RPPMQ==)
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

# Uncomment following codes to customize JWT configuration.
#jwt:
#  configuration:
#    ttl: 1800000
#    ttl-for-remember-me: 604800000

# ATTENTION: Production environment is not permitted to disable web security!
custom:
  configuration:
    ignores:
      # POST Requests need to be ignored.
      post:
        - "/auth/register"
        - "/auth/login"
        - "/auth/logout"
      get:
        - "/auth/check-username-uniqueness"
        - "/auth/check-email-uniqueness"
        - "/auth/validate-username/**"
        - "/user/get-avatar"
      # Request need to be ignored that matches pattern.
      pattern:
        - "/druid/**"
    web-security-disabled: false

logging:
  # Configure logging level for SFTP/JSCH
  level:
    com:
      jcraft:
        jsch: WARN

sftp:
  client:
    configuration:
      host: 172.16.238.12
      port: 22
      user: johnny
      password: atmoz@sftp
      directory: upload
      private-key:
      private-key-pass-phrase:
      session-cache-size: 20
      session-wait-timeout: 15000
