server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: ENC(Llhd3pDTnL4x1BmFutqGNJ2h3M/fw5OpKCDACf3vztgW/B2mtjle0SHqDE4XETHT)
    key-alias: tomcat

spring:
  cache:
    cache-names: c1,c2
    redis:
      time-to-live: 1800s
  datasource:
    name: datasource-one
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: ENC(YDztJDe/yC1bSMpzile1NZnZvNjUHCqK75mNSyFPGh5iOKeHYjYm8+CKbqqiYPK8OBi7QF541WDCtsjD20NoXD+GL4991Ng/l+fJ2L9mmOkuYslkG3SeAiPdtmxCu57KNAnhwHST3WibRgdxbbs/vItYyaUKTEAEwpCE2YxCoKc=)
    username: ENC(XIDh8RzZoA/R8/1DUCMYhDyV6N7jqlCSCHDgg2CjbGPz7dA3yWHCLQ==)
    password: ENC(m5mZkr93kta3P3230Rcr2qyxYlx3zRIjufbzHLY5m2s=)
  devtools:
    restart:
      enabled: false
  redis:
    database: 0
    host: ENC(NCJGHasDqzQCvOhNZWKzGGnbsuSKEEok)
    port: 6379
    password: ENC(aIqOVSt1Lsw/k1RN0RPPMQ==)
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

custom:
  configuration:
    ignores:
      # POST Requests need to be ignored.
      post:
        - "/auth/register"
        - "/auth/login"
      get:
        - "/auth/checkUsernameUniqueness"
        - "/auth/checkEmailUniqueness"
        - "/auth/validateUsername/**"
      # Request need to be ignored that matches pattern.
      pattern:
        - "/druid/**"
