server:
  servlet:
    context-path: /@parent.artifactId@-@envAlias@
  tomcat:
    uri-encoding: @project.build.sourceEncoding@

spring:
  application:
    name: @parent.name@
  messages:
    basename: i18n/messages
    encoding: @project.build.sourceEncoding@
  profiles:
    active: @env@
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      # `location` specifies the directory where uploaded files will be stored. When not specified,
      # a temporary directory will be used. ATTENTION: it may differ due to OS.
      location: /Users/johnny/Documents/@parent.artifactId@/temp
      # `max-file-size` specifies the maximum size permitted for uploaded files. The default is 1MB. We set it as 64 MB.
      max-file-size: 64MB
      # `max-request-size` specifies the maximum size allowed for multipart/form-data requests. The default is 10MB.
      max-request-size: 70MB
      # `file-size-threshold` specifies the size threshold after which files will be written to disk.
      # The default is 0. We set it as 0 too.
      file-size-threshold: 0

logging:
  config: classpath:configuration/logback/logback-@env@.xml
  # Configure logging level of project as DEBUG to enable SQL logging and other logging.
  level:
    com:
      jmframework:
        boot: DEBUG

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # mapper-locations should start with `classpath*` prefix
  # when project is based on Maven multi-module to load XML mapper in different jar
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  # FIXME: if enable type-aliases-package, unit tests won't start correctly with following exception:
  # nested exception is org.apache.ibatis.type.TypeException:
  # The alias '' is already mapped to the value 'com.jmframework.boot.jmspringbootstarter.config.JwtAuthenticationFilter$1'
  global-config:
    db-config:
      table-prefix: t_
#  type-aliases-package: @parent.groupId@

jasypt:
  encryptor:
    password: ThisIsAPrivateKeyOfJasypt

project:
  property:
    context-path: /@parent.artifactId@-@envAlias@
    group-id: @parent.groupId@
    artifact-id: @artifactId@
    project-artifact-id: @parent.artifactId@
    version: @parent.version@
    description: @project.description@
    jdk-version: @java.version@
    environment: @env@
    environment-alias: @envAlias@
    url: @project.url@
    inception-year: @inceptionYear@
    organization-name: @project.organization.name@
    organization-url: @project.organization.url@
    issue-management-system: @project.issueManagement.system@
    issue-management-url: @project.issueManagement.url@

custom:
  configuration:
    super-user: ENC(r9QJeNlK2nTb3uFQCi4P+w==)
    druid-login-name: ENC(v81zk6uOH72fTKZTWxbOgg==)
    druid-password: ENC(99HsmfWW2K8z3t1jUb0fZg==)
