server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: ENC(Llhd3pDTnL4x1BmFutqGNJ2h3M/fw5OpKCDACf3vztgW/B2mtjle0SHqDE4XETHT)
    key-alias: tomcat

spring:
  cache:
    cache-names: c1,c2
    redis:
      time-to-live: 1800s
  datasource:
    name: datasource-one
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: ENC(oykngxHQOtecuI91yXnyg8wDn1HtUJgKI3x4duidBtJ+mrlfS6sz1Ch37MPvgzCjBRZM4KZb7KoA8mr1pWDGxYBewxEtvF1OtDUfVlwosp2sotIUT084OjdSyLXGrw1f)
    username: ENC(iUSkjmrs8erSiLIOvS8Fpl6E7IPLC0TJ4wBoTdfUitE=)
    password: ENC(uyds+DW9Lw8KS0oLGbG7noXoGf0XR5Ak)
  devtools:
    restart:
      enabled: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password: ENC(lGKu2PTxVNCE8WQGPC0z2g==)
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

# Uncomment following codes to customize JWT configuration.
#jwt:
#  configuration:
#    ttl: 1800000
#    ttl-for-remember-me: 604800000

custom:
  configuration:
    # Make `web-security-disabled` equal to true to disable web security. We suggest you do not turn off web security
    # feature unless development environment.
    web-request-log-disabled: false
    ignores:
      # POST Requests need to be ignored.
      post:
        - "/auth/register"
        - "/auth/login"
      get:
        - "/auth/check-username-uniqueness"
        - "/auth/check-email-uniqueness"
        - "/auth/validate-username/**"
      # Request need to be ignored that matches pattern.
      pattern:
        - "/druid/**"
        - "/swagger-resources/**"
        - "/v2/api-docs/**"
        - "/webjars/**"
        - "/swagger-ui.html"

sftp:
  configuration:
    host: 127.0.0.1
    port: 22
    user: johnny
    password: jm@mac
    directory: /Users/johnny/Public
    private-key:
    private-key-pass-phrase:
