server:
  port: 8443
  # Comment following ssl configuration to DISABLE HTTPS in development environment.
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: ENC(Llhd3pDTnL4x1BmFutqGNJ2h3M/fw5OpKCDACf3vztgW/B2mtjle0SHqDE4XETHT)
    key-alias: tomcat

spring:
  cache:
    cache-names: c1,c2
    redis:
      time-to-live: 1800s
  datasource:
    name: datasource-one
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: ENC(TslQWVS/EIvdPZTmRBVdYxbU/yLyAFV0k0obxhBSIgg5u3SBIAYgcaaReO26roEIkSSCVFvkBU1Fuk1xXhDNax+D9gPQ0J8DvX2VQgYu0iIPjfHxHNezQJfsI2Lpr/gV5sNe5q2W4ih7zxsPEItN0jtQT3E5G42D+NZPNmhvVdQGH//JOQj9oHyG7e0A8JvpFvX7p0IwnPGnZLO2A2ZHxedOu4TTrcisFUzr+kE8SEIAhWJhgpAHiaLemdri1DIbkOh64eUFUPA=)
    username: ENC(4lska00DO+25XyMZdKMuxHQ+J92OkgENbKR39qoZW+6ivJvpeFYlMQ==)
    password: ENC(MWH3LrbDDSXIvUpT/WLbvofKW2x/nxr/)
  devtools:
    restart:
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: ENC(lGKu2PTxVNCE8WQGPC0z2g==)
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

# Customize JWT configuration for development environment.
jwt:
  configuration:
    # an hour
    ttl: 3600000
    ttl-for-remember-me: 604800000

custom:
  configuration:
    # Make `web-security-disabled` equal to true to disable web security. We suggest you do not turn off web security
    # feature unless development environment.
    web-security-disabled: true
    # Disable web request information log
    web-request-log-disabled: false
    ignores:
      # POST Requests need to be ignored.
      post:
        - "/auth/register"
        - "/auth/login"
      get:
        - "/auth/check-username-uniqueness"
        - "/auth/check-email-uniqueness"
        - "/auth/validate-username/**"
      # Request need to be ignored that matches pattern.
      pattern:
        - "/druid/**"
        - "/swagger-resources/**"
        - "/v2/api-docs/**"
        - "/webjars/**"
        - "/swagger-ui.html"

sftp:
  client:
    configuration:
      host: ENC(1XwJZpHiJTHb9lwN1E4dIsK4b2hYUkub)
      port: 22
      user: ENC(GYQSxdqkQuwd+7n46ICczw==)
      password: ENC(KrwHjLICKJTgt7+Oye6VlQ==)
      directory: ENC(Mf+uGv44ofMSEgEB21IzK7jATGWNOCZL1KcqHpDRRcs=)
      private-key:
      private-key-pass-phrase:
